//USER
export const UPDATE_USER = 'UPDATE_USER';
export const RESET_USER = 'RESET_USER';

// DASHBOARD
export const FETCH_EVENTS_START = 'FETCH_EVENTS_START';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL';

export const FILTER_EVENTS_START = 'FILTER_EVENTS_START';
export const FILTER_EVENTS_SUCCESS = 'FILTER_EVENTS_SUCCESS';
export const FILTER_EVENTS_FAIL = 'FILTER_EVENTS_FAIL';

export const UPDATE_EVENT_BOOKING = 'UPDATE_EVENT_BOOKING';
export const UPDATE_EVENT_DURATION = 'UPDATE_EVENT_DURATION';

export const SHOW_BOOKING_MODAL = 'SHOW_BOOKING_MODAL';
export const HIDE_BOOKING_MODAL = 'HIDE_BOOKING_MODAL';
