//USER
export const UPDATE_USER = 'UPDATE_USER';
export const RESET_USER = 'RESET_USER';

// DASHBOARD

export const UPDATE_EVENT_BOOKING = 'UPDATE_EVENT_BOOKING';
export const UPDATE_EVENT_DURATION = 'UPDATE_EVENT_DURATION';

export const TOGGLE_BOOKING_MODAL = 'TOGGLE_BOOKING_MODAL';

export const SET_IS_BEING_UPDATED = 'SET_IS_BEING_UPDATED';
export const SET_CALENDAR_EVENTS = 'SET_CALENDAR_EVENTS';
export const SET_ERROR = 'SET_ERROR';
